logging:
  level: info # Logging level: debug, info, warn, error
server:
  # Server mode: "sse" (HTTP+SSE) or "stdio" (stdin/stdout)
  mode: sse
  sse:
    host: 0.0.0.0 # SSE server host (0.0.0.0 allows external connections)
    port: 8910 # SSE server port
    # REQUIRED for SSE mode: Token for Bearer authentication
    # Generate a secure random token: openssl rand -base64 32
    token: your_secure_token_here
tmdb:
  # # REQUIRED: Your TMDB API Key (get from https://www.themoviedb.org/settings/api)
  api_key: your_tmdb_api_key_here # TMDB API secret key
  language: zh-CN # TMDB API language (ISO 639-1 code)
  rate_limit: 40 # TMDB API rate limit (number of requests every 10 seconds)
